server:
  port: 8083

spring:
  application:
    name: user
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
    validate-on-migrate: false
    url: jdbc:${DB_TYPE}://${DB_HOST}:${DB_PORT}/${DB_NAME}
    user: ${DB_USER}
    password: ${DB_PASSWORD}
    locations:
      - classpath:db/migration
    enabled: true

database:
  url: jdbc:${DB_TYPE}://${DB_HOST}:${DB_PORT}/
  name: ${DB_NAME}
  username: ${DB_USER}
  password: ${DB_PASSWORD}
  driverClassName: org.postgresql.Driver
  createIfNotExist: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000 # Bağlantı zaman aşımı (ms)
        readTimeout: 5000    # Okuma zaman aşımı (ms)
  logger:
    level: full            # Feign istemcisinin günlükleme seviyesi (full, basic, headers, none)

jwt:
  secret: a9e57b4087d4cabcbd8f5ca85b38398a0a52ebd603d302e721892f460beaaddf
  expiration: 240


DB_TYPE: postgresql
DB_HOST: localhost
DB_PORT: 5432
DB_NAME: company_user
DB_USER: admin
DB_PASSWORD: admin123