version: '3.8'

services:
  postgres:
    container_name: company
    image: postgres
    read_only: true
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin123
    ports:
      - "5432:5432"
    expose:
      - "5432"
    tmpfs:
      - /tmp
      - /run
      - /run/postgresql
    volumes:
      - postgres:/data/postgres
    command: -p 5432
volumes:
  postgres: