server:
  port: 8082

spring:
  application:
    name: product
employee:
  url: http://localhost:8081
# Feign istemcisi yapılandırması
feign:
  client:

    config:
      default:
        connectTimeout: 5000 # Bağlantı zaman aşımı (ms)
        readTimeout: 5000    # Okuma zaman aşımı (ms)
  logger:
    level: full            # Feign istemcisinin günlükleme seviyesi (full, basic, headers, none)