server:
  port: 8081

spring:
  application:
    name: employee
  datasource:
    url: jdbc:postgresql://localhost:5432/company-employee?createDatabaseIfNotExist=true
    username: admin
    password: admin123
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


feign:
  client:
    config:
      default:
        connectTimeout: 5000 # Bağlantı zaman aşımı (ms)
        readTimeout: 5000    # Okuma zaman aşımı (ms)
  logger:
    level: full            # Feign istemcisinin günlükleme seviyesi (full, basic, headers, none)